fastlane_require 'dotenv'

default_platform(:ios)

ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = "60"
ENV['FASTLANE_XCODEBUILD_SETTINGS_RETRIES'] = "10"

# - Variables

module_name = "Project"
precompiled_folder_path = "Precompiled"
build_folder_path = ".build"
precompiled_xcframework_path = "#{precompiled_folder_path}/Project.xcframework"
xcodeproj_path = "Project.xcodeproj"
pbxproj_path = "#{xcodeproj_path}/project.pbxproj"
podspec_path = "Project.podspec"

# - Lanes

update_fastlane

platform :ios do

  before_all do |lane, options|
    Dotenv.overload '.env.secret'
  end

  desc "Runs module unit tests"
  lane :test do 
    run_tests(scheme: module_name)
  end

  desc "Releases a new version of the module and returns its RELEASE_ID"
  lane :prepare_release do |options|
    version = options[:version]

    set_marketing_version(version: version)
    build_xcframework
    release_to_github(version: version)
    update_podspec(version: version)
  end

  # - Private

  private_lane :set_marketing_version do |options|
    version = options[:version]

    increment_version_number_in_xcodeproj(
      version_number: version,     
      xcodeproj: xcodeproj_path
    )
    git_commit(
      path: [pbxproj_path],
      message: "[skip ci] Set module version to #{version}",
      allow_nothing_to_commit: true
    )
  end

  private_lane :build_xcframework do 
    precompile_module(
      scheme_name: module_name,
      module_name: module_name,
      output_dir: precompiled_folder_path
    )
  end

  private_lane :release_to_github do |options|
    version = options[:version]

    set_github_release(
      repository_name: github_repository_name,
      tag_name: version,
      api_token: github_api_token,
      upload_assets: [precompiled_xcframework_path],
      is_prerelease: true
    )
  end

  private_lane :update_podspec do |options|
    binary_source = github_release_uploaded_binary_url
    version = options[:version]

    version_bump_podspec(
      path: podspec_path,
      version_number: version
    )
    set_podspec_http_source(
      binary_zip_path: binary_source,
      podspec_path: podspec_path
    )
    git_commit(
      path: [podspec_path],
      message: "[skip ci] Update podspec",
      allow_nothing_to_commit: true
    )
  end

  private_lane :clean_up do
    clean_outputs(output_dir: precompiled_folder_path)
  end  

  after_all do |lane, options|
    clean_up
  end

  error do |lane, exception, options|
    clean_up
  end

end

# - Utils

def github_api_token
  ENV['GITHUB_API_TOKEN']
end

def github_repository_name
  ENV['GITHUB_REPOSITORY_NAME']
end

def github_release_uploaded_binary_url
  assets = lane_context[SharedValues::SET_GITHUB_RELEASE_JSON]['assets']
  assets.first['browser_download_url']
end