{"variants":[{"paths":["\/documentation\/project"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/project"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/kkuc-sa.Project\/documentation\/Project","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/kkuc-sa.Project\/documentation\/Project\/Class"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"Project","title":"Project","symbolKind":"module","role":"collection","modules":[{"name":"Project"}]},"hierarchy":{"paths":[[]]},"references":{"doc://kkuc-sa.Project/documentation/Project/Class":{"role":"symbol","title":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Class"}],"abstract":[{"type":"text","text":"Represents a class that does sth."}],"identifier":"doc:\/\/kkuc-sa.Project\/documentation\/Project\/Class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Class"}],"url":"\/documentation\/project\/class"},"doc://kkuc-sa.Project/documentation/Project":{"role":"collection","title":"Project","abstract":[],"identifier":"doc:\/\/kkuc-sa.Project\/documentation\/Project","kind":"symbol","type":"topic","url":"\/documentation\/project"},"doc://kkuc-sa.Project/documentation/Project/ProjectVersionNumber":{"role":"symbol","title":"ProjectVersionNumber","fragments":[{"kind":"identifier","text":"ProjectVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for Project."}],"identifier":"doc:\/\/kkuc-sa.Project\/documentation\/Project\/ProjectVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/project\/projectversionnumber"},"doc://kkuc-sa.Project/documentation/Project/ProjectVersionString":{"role":"symbol","title":"ProjectVersionString","fragments":[{"kind":"identifier","text":"ProjectVersionString"}],"abstract":[{"type":"text","text":"Project version string for Project."}],"identifier":"doc:\/\/kkuc-sa.Project\/documentation\/Project\/ProjectVersionString","kind":"symbol","type":"topic","url":"\/documentation\/project\/projectversionstring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/kkuc-sa.Project\/documentation\/Project\/ProjectVersionNumber","doc:\/\/kkuc-sa.Project\/documentation\/Project\/ProjectVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}