name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version  (ie 5.5.0)'
        required: true

jobs:
  create_release:
    # runs-on: macos-13
    runs-on: ubuntu-latest
    timeout-minutes: 29
    steps:

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Set up ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true

    - name: Config Git
      run: |
        git config user.name "CI Bot"
        git config user.email noreply@github.com

    - name: Create release branch
      run: git checkout -b release/${{ github.event.inputs.version }}

    - name: Set MARKETING_VERSION
      run: bundle exec fastlane set_marketing_version version:${{ github.event.inputs.version }}

    - name: Update docs
      env:
        HOSTING_BASE_PATH: {{ github.event.repository.name }}
      run: |
        sh scripts/generate_docs.sh
        git add docs/
        git commit --message "[skip ci] Update docs"

    - name: Push release branch
      run: git push origin release/${{ github.event.inputs.version }}

    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        head: release/${{ github.event.inputs.version }}
        base: main
        title: ${{ github.event.inputs.version }} into main