name: Publish release

on:
  push:
    branches:
    - main

jobs:
  publish_release:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged
    steps:

    - name: Echo sth
      run: echo 'sth'

    # - name: Extract version from branch name (for release branches)
    #   if: startsWith(github.event.pull_request.head.ref, 'release/')
    #   run: |
    #     BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
    #     VERSION=${BRANCH_NAME#release/}

    #     echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

    # - name: Extract version from branch name (for hotfix branches)
    #   if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
    #   run: |
    #     BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
    #     VERSION=${BRANCH_NAME#hotfix/}

    #     echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

    # - name: Update release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     allowUpdates: true
    #     tag: ${{ env.RELEASE_VERSION }}