name: Publish release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish_release:
    if: startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:

    - name: Extract version from branch name (for release branches)
      if: startsWith(github.event.pull_request.head.ref, 'release/')
      run: |
        BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
        VERSION=${BRANCH_NAME#release/}
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Extract version from branch name (for hotfix branches)
      if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
      run: |
        BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
        VERSION=${BRANCH_NAME#hotfix/}
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Set up ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true

    - name: Update release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: ${{ env.RELEASE_VERSION }}

    - name: Publish pod
      run: bundle exec pod spec lint