name: Run tests

on: workflow_dispatch

jobs:  
  test:
    runs-on: macos-12
    timeout-minutes: 29
    steps:

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Set up ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true

    - name: Unit tests
      run: bundle exec fastlane test